#!/bin/bash
BASE_VERSION='base'
cat Dockerfile.template  | sed "s/VERSION/${BASE_VERSION}/" > Dockerfile
echo Make sure dockerfile has ${BASE_VERSION} for base image
export githash=`git rev-parse --short HEAD`
docker build --tag opentaproject/ww-renderer-openta:${VERSION} .
docker push opentaproject/ww-renderer-openta:${VERSION}
docker tag opentaproject/ww-renderer-openta:${VERSION} opentaproject/ww-renderer-openta:${githash}
docker push opentaproject/ww-renderer-openta:${VERSION}
